/**
 * Generated for AVR code. Do not edit.
 * This file is generated by using the avr-gcc compiler configuration.
 * This will include the architecture specific headers by using the
 * macro names like ARDO_MCU_ARCH_INCLUDE_{{mcu_arch}}. Multiple achitecture
 * specific header files can be included if multiple ARDO_MCU_ARCH_INCLUDE_...
 * macros are defined. The mcu_arch with the ARDO_MCU_ARCH_NAME defined
 * will cause the namespace for that architecture to be aliased to 
 * ardo::sys::avr::mcu. If the ARDO_MCU_ARCH_NAME is defined before loading
 * this file, the compiler arch setting is ignored.
 */

#ifndef ardo_mcu_avr_defs__h
#define ardo_mcu_avr_defs__h

#define ARDO_MCU_ARCH_NAMESPACE_(arch_name) arch_ ## arch_name
#define ARDO_MCU_ARCH_NAMESPACE(arch_name) ARDO_MCU_ARCH_NAMESPACE_(arch_name)

#if defined(ARDO_MCU_ARCH_NAME)
#pragma message("MCU architecture is overridden, compiler's mcu arch setting ignored.")
#elif defined(__AVR_AT43USB320__)
#define ARDO_MCU_ARCH_INCLUDE_at43usb320 1
#define ARDO_MCU_ARCH_NAME at43usb320
#elif defined(__AVR_AT43USB355__)
#define ARDO_MCU_ARCH_INCLUDE_at43usb355 1
#define ARDO_MCU_ARCH_NAME at43usb355
#elif defined(__AVR_AT76C711__)
#define ARDO_MCU_ARCH_INCLUDE_at76c711 1
#define ARDO_MCU_ARCH_NAME at76c711
#elif defined(__AVR_AT86RF401__)
#define ARDO_MCU_ARCH_INCLUDE_at86rf401 1
#define ARDO_MCU_ARCH_NAME at86rf401
#elif defined(__AVR_AT90C8534__)
#define ARDO_MCU_ARCH_INCLUDE_at90c8534 1
#define ARDO_MCU_ARCH_NAME at90c8534
#elif defined(__AVR_AT90CAN128__)
#define ARDO_MCU_ARCH_INCLUDE_at90can128 1
#define ARDO_MCU_ARCH_NAME at90can128
#elif defined(__AVR_AT90CAN32__)
#define ARDO_MCU_ARCH_INCLUDE_at90can32 1
#define ARDO_MCU_ARCH_NAME at90can32
#elif defined(__AVR_AT90CAN64__)
#define ARDO_MCU_ARCH_INCLUDE_at90can64 1
#define ARDO_MCU_ARCH_NAME at90can64
#elif defined(__AVR_AT90PWM1__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm1 1
#define ARDO_MCU_ARCH_NAME at90pwm1
#elif defined(__AVR_AT90PWM161__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm161 1
#define ARDO_MCU_ARCH_NAME at90pwm161
#elif defined(__AVR_AT90PWM2__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm2 1
#define ARDO_MCU_ARCH_NAME at90pwm2
#elif defined(__AVR_AT90PWM216__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm216 1
#define ARDO_MCU_ARCH_NAME at90pwm216
#elif defined(__AVR_AT90PWM2B__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm2b 1
#define ARDO_MCU_ARCH_NAME at90pwm2b
#elif defined(__AVR_AT90PWM3__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm3 1
#define ARDO_MCU_ARCH_NAME at90pwm3
#elif defined(__AVR_AT90PWM316__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm316 1
#define ARDO_MCU_ARCH_NAME at90pwm316
#elif defined(__AVR_AT90PWM3B__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm3b 1
#define ARDO_MCU_ARCH_NAME at90pwm3b
#elif defined(__AVR_AT90PWM81__)
#define ARDO_MCU_ARCH_INCLUDE_at90pwm81 1
#define ARDO_MCU_ARCH_NAME at90pwm81
#elif defined(__AVR_AT90S1200__)
#define ARDO_MCU_ARCH_INCLUDE_at90s1200 1
#define ARDO_MCU_ARCH_NAME at90s1200
#elif defined(__AVR_AT90S2313__)
#define ARDO_MCU_ARCH_INCLUDE_at90s2313 1
#define ARDO_MCU_ARCH_NAME at90s2313
#elif defined(__AVR_AT90S2323__)
#define ARDO_MCU_ARCH_INCLUDE_at90s2323 1
#define ARDO_MCU_ARCH_NAME at90s2323
#elif defined(__AVR_AT90S2333__)
#define ARDO_MCU_ARCH_INCLUDE_at90s2333 1
#define ARDO_MCU_ARCH_NAME at90s2333
#elif defined(__AVR_AT90S2343__)
#define ARDO_MCU_ARCH_INCLUDE_at90s2343 1
#define ARDO_MCU_ARCH_NAME at90s2343
#elif defined(__AVR_AT90S4414__)
#define ARDO_MCU_ARCH_INCLUDE_at90s4414 1
#define ARDO_MCU_ARCH_NAME at90s4414
#elif defined(__AVR_AT90S4433__)
#define ARDO_MCU_ARCH_INCLUDE_at90s4433 1
#define ARDO_MCU_ARCH_NAME at90s4433
#elif defined(__AVR_AT90S4434__)
#define ARDO_MCU_ARCH_INCLUDE_at90s4434 1
#define ARDO_MCU_ARCH_NAME at90s4434
#elif defined(__AVR_AT90S8515__)
#define ARDO_MCU_ARCH_INCLUDE_at90s8515 1
#define ARDO_MCU_ARCH_NAME at90s8515
#elif defined(__AVR_AT90S8535__)
#define ARDO_MCU_ARCH_INCLUDE_at90s8535 1
#define ARDO_MCU_ARCH_NAME at90s8535
#elif defined(__AVR_AT90SCR100__)
#define ARDO_MCU_ARCH_INCLUDE_at90scr100 1
#define ARDO_MCU_ARCH_NAME at90scr100
#elif defined(__AVR_AT90USB1286__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb1286 1
#define ARDO_MCU_ARCH_NAME at90usb1286
#elif defined(__AVR_AT90USB1287__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb1287 1
#define ARDO_MCU_ARCH_NAME at90usb1287
#elif defined(__AVR_AT90USB162__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb162 1
#define ARDO_MCU_ARCH_NAME at90usb162
#elif defined(__AVR_AT90USB646__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb646 1
#define ARDO_MCU_ARCH_NAME at90usb646
#elif defined(__AVR_AT90USB647__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb647 1
#define ARDO_MCU_ARCH_NAME at90usb647
#elif defined(__AVR_AT90USB82__)
#define ARDO_MCU_ARCH_INCLUDE_at90usb82 1
#define ARDO_MCU_ARCH_NAME at90usb82
#elif defined(__AVR_AT94K__)
#define ARDO_MCU_ARCH_INCLUDE_at94k 1
#define ARDO_MCU_ARCH_NAME at94k
#elif defined(__AVR_ATA5272__)
#define ARDO_MCU_ARCH_INCLUDE_ata5272 1
#define ARDO_MCU_ARCH_NAME ata5272
#elif defined(__AVR_ATA5505__)
#define ARDO_MCU_ARCH_INCLUDE_ata5505 1
#define ARDO_MCU_ARCH_NAME ata5505
#elif defined(__AVR_ATA5702M322__)
#define ARDO_MCU_ARCH_INCLUDE_ata5702m322 1
#define ARDO_MCU_ARCH_NAME ata5702m322
#elif defined(__AVR_ATA5782__)
#define ARDO_MCU_ARCH_INCLUDE_ata5782 1
#define ARDO_MCU_ARCH_NAME ata5782
#elif defined(__AVR_ATA5790__)
#define ARDO_MCU_ARCH_INCLUDE_ata5790 1
#define ARDO_MCU_ARCH_NAME ata5790
#elif defined(__AVR_ATA5790N__)
#define ARDO_MCU_ARCH_INCLUDE_ata5790n 1
#define ARDO_MCU_ARCH_NAME ata5790n
#elif defined(__AVR_ATA5791__)
#define ARDO_MCU_ARCH_INCLUDE_ata5791 1
#define ARDO_MCU_ARCH_NAME ata5791
#elif defined(__AVR_ATA5795__)
#define ARDO_MCU_ARCH_INCLUDE_ata5795 1
#define ARDO_MCU_ARCH_NAME ata5795
#elif defined(__AVR_ATA5831__)
#define ARDO_MCU_ARCH_INCLUDE_ata5831 1
#define ARDO_MCU_ARCH_NAME ata5831
#elif defined(__AVR_ATA6285__)
#define ARDO_MCU_ARCH_INCLUDE_ata6285 1
#define ARDO_MCU_ARCH_NAME ata6285
#elif defined(__AVR_ATA6286__)
#define ARDO_MCU_ARCH_INCLUDE_ata6286 1
#define ARDO_MCU_ARCH_NAME ata6286
#elif defined(__AVR_ATA6289__)
#define ARDO_MCU_ARCH_INCLUDE_ata6289 1
#define ARDO_MCU_ARCH_NAME ata6289
#elif defined(__AVR_ATA6612C__)
#define ARDO_MCU_ARCH_INCLUDE_ata6612c 1
#define ARDO_MCU_ARCH_NAME ata6612c
#elif defined(__AVR_ATA6613C__)
#define ARDO_MCU_ARCH_INCLUDE_ata6613c 1
#define ARDO_MCU_ARCH_NAME ata6613c
#elif defined(__AVR_ATA6614Q__)
#define ARDO_MCU_ARCH_INCLUDE_ata6614q 1
#define ARDO_MCU_ARCH_NAME ata6614q
#elif defined(__AVR_ATA6616C__)
#define ARDO_MCU_ARCH_INCLUDE_ata6616c 1
#define ARDO_MCU_ARCH_NAME ata6616c
#elif defined(__AVR_ATA6617C__)
#define ARDO_MCU_ARCH_INCLUDE_ata6617c 1
#define ARDO_MCU_ARCH_NAME ata6617c
#elif defined(__AVR_ATA664251__)
#define ARDO_MCU_ARCH_INCLUDE_ata664251 1
#define ARDO_MCU_ARCH_NAME ata664251
#elif defined(__AVR_ATA8210__)
#define ARDO_MCU_ARCH_INCLUDE_ata8210 1
#define ARDO_MCU_ARCH_NAME ata8210
#elif defined(__AVR_ATA8510__)
#define ARDO_MCU_ARCH_INCLUDE_ata8510 1
#define ARDO_MCU_ARCH_NAME ata8510
#elif defined(__AVR_ATmega103__)
#define ARDO_MCU_ARCH_INCLUDE_atmega103 1
#define ARDO_MCU_ARCH_NAME atmega103
#elif defined(__AVR_ATmega128__)
#define ARDO_MCU_ARCH_INCLUDE_atmega128 1
#define ARDO_MCU_ARCH_NAME atmega128
#elif defined(__AVR_ATmega1280__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1280 1
#define ARDO_MCU_ARCH_NAME atmega1280
#elif defined(__AVR_ATmega1281__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1281 1
#define ARDO_MCU_ARCH_NAME atmega1281
#elif defined(__AVR_ATmega1284__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1284 1
#define ARDO_MCU_ARCH_NAME atmega1284
#elif defined(__AVR_ATmega1284P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1284p 1
#define ARDO_MCU_ARCH_NAME atmega1284p
#elif defined(__AVR_ATmega1284RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1284rfr2 1
#define ARDO_MCU_ARCH_NAME atmega1284rfr2
#elif defined(__AVR_ATmega128A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega128a 1
#define ARDO_MCU_ARCH_NAME atmega128a
#elif defined(__AVR_ATmega128RFA1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega128rfa1 1
#define ARDO_MCU_ARCH_NAME atmega128rfa1
#elif defined(__AVR_ATmega128RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega128rfr2 1
#define ARDO_MCU_ARCH_NAME atmega128rfr2
#elif defined(__AVR_ATmega16__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16 1
#define ARDO_MCU_ARCH_NAME atmega16
#elif defined(__AVR_ATmega1608__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1608 1
#define ARDO_MCU_ARCH_NAME atmega1608
#elif defined(__AVR_ATmega1609__)
#define ARDO_MCU_ARCH_INCLUDE_atmega1609 1
#define ARDO_MCU_ARCH_NAME atmega1609
#elif defined(__AVR_ATmega161__)
#define ARDO_MCU_ARCH_INCLUDE_atmega161 1
#define ARDO_MCU_ARCH_NAME atmega161
#elif defined(__AVR_ATmega162__)
#define ARDO_MCU_ARCH_INCLUDE_atmega162 1
#define ARDO_MCU_ARCH_NAME atmega162
#elif defined(__AVR_ATmega163__)
#define ARDO_MCU_ARCH_INCLUDE_atmega163 1
#define ARDO_MCU_ARCH_NAME atmega163
#elif defined(__AVR_ATmega164A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega164a 1
#define ARDO_MCU_ARCH_NAME atmega164a
#elif defined(__AVR_ATmega164P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega164p 1
#define ARDO_MCU_ARCH_NAME atmega164p
#elif defined(__AVR_ATmega164PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega164pa 1
#define ARDO_MCU_ARCH_NAME atmega164pa
#elif defined(__AVR_ATmega165__)
#define ARDO_MCU_ARCH_INCLUDE_atmega165 1
#define ARDO_MCU_ARCH_NAME atmega165
#elif defined(__AVR_ATmega165A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega165a 1
#define ARDO_MCU_ARCH_NAME atmega165a
#elif defined(__AVR_ATmega165P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega165p 1
#define ARDO_MCU_ARCH_NAME atmega165p
#elif defined(__AVR_ATmega165PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega165pa 1
#define ARDO_MCU_ARCH_NAME atmega165pa
#elif defined(__AVR_ATmega168__)
#define ARDO_MCU_ARCH_INCLUDE_atmega168 1
#define ARDO_MCU_ARCH_NAME atmega168
#elif defined(__AVR_ATmega168A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega168a 1
#define ARDO_MCU_ARCH_NAME atmega168a
#elif defined(__AVR_ATmega168P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega168p 1
#define ARDO_MCU_ARCH_NAME atmega168p
#elif defined(__AVR_ATmega168PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega168pa 1
#define ARDO_MCU_ARCH_NAME atmega168pa
#elif defined(__AVR_ATmega168PB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega168pb 1
#define ARDO_MCU_ARCH_NAME atmega168pb
#elif defined(__AVR_ATmega169__)
#define ARDO_MCU_ARCH_INCLUDE_atmega169 1
#define ARDO_MCU_ARCH_NAME atmega169
#elif defined(__AVR_ATmega169A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega169a 1
#define ARDO_MCU_ARCH_NAME atmega169a
#elif defined(__AVR_ATmega169P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega169p 1
#define ARDO_MCU_ARCH_NAME atmega169p
#elif defined(__AVR_ATmega169PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega169pa 1
#define ARDO_MCU_ARCH_NAME atmega169pa
#elif defined(__AVR_ATmega16A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16a 1
#define ARDO_MCU_ARCH_NAME atmega16a
#elif defined(__AVR_ATmega16HVA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16hva 1
#define ARDO_MCU_ARCH_NAME atmega16hva
#elif defined(__AVR_ATmega16HVA2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16hva2 1
#define ARDO_MCU_ARCH_NAME atmega16hva2
#elif defined(__AVR_ATmega16HVB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16hvb 1
#define ARDO_MCU_ARCH_NAME atmega16hvb
#elif defined(__AVR_ATmega16HVBREVB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16hvbrevb 1
#define ARDO_MCU_ARCH_NAME atmega16hvbrevb
#elif defined(__AVR_ATmega16M1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16m1 1
#define ARDO_MCU_ARCH_NAME atmega16m1
#elif defined(__AVR_ATmega16U2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16u2 1
#define ARDO_MCU_ARCH_NAME atmega16u2
#elif defined(__AVR_ATmega16U4__)
#define ARDO_MCU_ARCH_INCLUDE_atmega16u4 1
#define ARDO_MCU_ARCH_NAME atmega16u4
#elif defined(__AVR_ATmega2560__)
#define ARDO_MCU_ARCH_INCLUDE_atmega2560 1
#define ARDO_MCU_ARCH_NAME atmega2560
#elif defined(__AVR_ATmega2561__)
#define ARDO_MCU_ARCH_INCLUDE_atmega2561 1
#define ARDO_MCU_ARCH_NAME atmega2561
#elif defined(__AVR_ATmega2564RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega2564rfr2 1
#define ARDO_MCU_ARCH_NAME atmega2564rfr2
#elif defined(__AVR_ATmega256RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega256rfr2 1
#define ARDO_MCU_ARCH_NAME atmega256rfr2
#elif defined(__AVR_ATmega32__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32 1
#define ARDO_MCU_ARCH_NAME atmega32
#elif defined(__AVR_ATmega3208__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3208 1
#define ARDO_MCU_ARCH_NAME atmega3208
#elif defined(__AVR_ATmega3209__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3209 1
#define ARDO_MCU_ARCH_NAME atmega3209
#elif defined(__AVR_ATmega323__)
#define ARDO_MCU_ARCH_INCLUDE_atmega323 1
#define ARDO_MCU_ARCH_NAME atmega323
#elif defined(__AVR_ATmega324A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega324a 1
#define ARDO_MCU_ARCH_NAME atmega324a
#elif defined(__AVR_ATmega324P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega324p 1
#define ARDO_MCU_ARCH_NAME atmega324p
#elif defined(__AVR_ATmega324PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega324pa 1
#define ARDO_MCU_ARCH_NAME atmega324pa
#elif defined(__AVR_ATmega324PB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega324pb 1
#define ARDO_MCU_ARCH_NAME atmega324pb
#elif defined(__AVR_ATmega325__)
#define ARDO_MCU_ARCH_INCLUDE_atmega325 1
#define ARDO_MCU_ARCH_NAME atmega325
#elif defined(__AVR_ATmega3250__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3250 1
#define ARDO_MCU_ARCH_NAME atmega3250
#elif defined(__AVR_ATmega3250A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3250a 1
#define ARDO_MCU_ARCH_NAME atmega3250a
#elif defined(__AVR_ATmega3250P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3250p 1
#define ARDO_MCU_ARCH_NAME atmega3250p
#elif defined(__AVR_ATmega3250PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3250pa 1
#define ARDO_MCU_ARCH_NAME atmega3250pa
#elif defined(__AVR_ATmega325A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega325a 1
#define ARDO_MCU_ARCH_NAME atmega325a
#elif defined(__AVR_ATmega325P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega325p 1
#define ARDO_MCU_ARCH_NAME atmega325p
#elif defined(__AVR_ATmega325PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega325pa 1
#define ARDO_MCU_ARCH_NAME atmega325pa
#elif defined(__AVR_ATmega328__)
#define ARDO_MCU_ARCH_INCLUDE_atmega328 1
#define ARDO_MCU_ARCH_NAME atmega328
#elif defined(__AVR_ATmega328P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega328p 1
#define ARDO_MCU_ARCH_NAME atmega328p
#elif defined(__AVR_ATmega328PB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega328pb 1
#define ARDO_MCU_ARCH_NAME atmega328pb
#elif defined(__AVR_ATmega329__)
#define ARDO_MCU_ARCH_INCLUDE_atmega329 1
#define ARDO_MCU_ARCH_NAME atmega329
#elif defined(__AVR_ATmega3290__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3290 1
#define ARDO_MCU_ARCH_NAME atmega3290
#elif defined(__AVR_ATmega3290A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3290a 1
#define ARDO_MCU_ARCH_NAME atmega3290a
#elif defined(__AVR_ATmega3290P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3290p 1
#define ARDO_MCU_ARCH_NAME atmega3290p
#elif defined(__AVR_ATmega3290PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega3290pa 1
#define ARDO_MCU_ARCH_NAME atmega3290pa
#elif defined(__AVR_ATmega329A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega329a 1
#define ARDO_MCU_ARCH_NAME atmega329a
#elif defined(__AVR_ATmega329P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega329p 1
#define ARDO_MCU_ARCH_NAME atmega329p
#elif defined(__AVR_ATmega329PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega329pa 1
#define ARDO_MCU_ARCH_NAME atmega329pa
#elif defined(__AVR_ATmega32A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32a 1
#define ARDO_MCU_ARCH_NAME atmega32a
#elif defined(__AVR_ATmega32C1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32c1 1
#define ARDO_MCU_ARCH_NAME atmega32c1
#elif defined(__AVR_ATmega32HVB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32hvb 1
#define ARDO_MCU_ARCH_NAME atmega32hvb
#elif defined(__AVR_ATmega32HVBREVB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32hvbrevb 1
#define ARDO_MCU_ARCH_NAME atmega32hvbrevb
#elif defined(__AVR_ATmega32M1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32m1 1
#define ARDO_MCU_ARCH_NAME atmega32m1
#elif defined(__AVR_ATmega32U2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32u2 1
#define ARDO_MCU_ARCH_NAME atmega32u2
#elif defined(__AVR_ATmega32U4__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32u4 1
#define ARDO_MCU_ARCH_NAME atmega32u4
#elif defined(__AVR_ATmega32U6__)
#define ARDO_MCU_ARCH_INCLUDE_atmega32u6 1
#define ARDO_MCU_ARCH_NAME atmega32u6
#elif defined(__AVR_ATmega406__)
#define ARDO_MCU_ARCH_INCLUDE_atmega406 1
#define ARDO_MCU_ARCH_NAME atmega406
#elif defined(__AVR_ATmega48__)
#define ARDO_MCU_ARCH_INCLUDE_atmega48 1
#define ARDO_MCU_ARCH_NAME atmega48
#elif defined(__AVR_ATmega4808__)
#define ARDO_MCU_ARCH_INCLUDE_atmega4808 1
#define ARDO_MCU_ARCH_NAME atmega4808
#elif defined(__AVR_ATmega4809__)
#define ARDO_MCU_ARCH_INCLUDE_atmega4809 1
#define ARDO_MCU_ARCH_NAME atmega4809
#elif defined(__AVR_ATmega48A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega48a 1
#define ARDO_MCU_ARCH_NAME atmega48a
#elif defined(__AVR_ATmega48P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega48p 1
#define ARDO_MCU_ARCH_NAME atmega48p
#elif defined(__AVR_ATmega48PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega48pa 1
#define ARDO_MCU_ARCH_NAME atmega48pa
#elif defined(__AVR_ATmega48PB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega48pb 1
#define ARDO_MCU_ARCH_NAME atmega48pb
#elif defined(__AVR_ATmega64__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64 1
#define ARDO_MCU_ARCH_NAME atmega64
#elif defined(__AVR_ATmega640__)
#define ARDO_MCU_ARCH_INCLUDE_atmega640 1
#define ARDO_MCU_ARCH_NAME atmega640
#elif defined(__AVR_ATmega644__)
#define ARDO_MCU_ARCH_INCLUDE_atmega644 1
#define ARDO_MCU_ARCH_NAME atmega644
#elif defined(__AVR_ATmega644A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega644a 1
#define ARDO_MCU_ARCH_NAME atmega644a
#elif defined(__AVR_ATmega644P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega644p 1
#define ARDO_MCU_ARCH_NAME atmega644p
#elif defined(__AVR_ATmega644PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega644pa 1
#define ARDO_MCU_ARCH_NAME atmega644pa
#elif defined(__AVR_ATmega644RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega644rfr2 1
#define ARDO_MCU_ARCH_NAME atmega644rfr2
#elif defined(__AVR_ATmega645__)
#define ARDO_MCU_ARCH_INCLUDE_atmega645 1
#define ARDO_MCU_ARCH_NAME atmega645
#elif defined(__AVR_ATmega6450__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6450 1
#define ARDO_MCU_ARCH_NAME atmega6450
#elif defined(__AVR_ATmega6450A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6450a 1
#define ARDO_MCU_ARCH_NAME atmega6450a
#elif defined(__AVR_ATmega6450P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6450p 1
#define ARDO_MCU_ARCH_NAME atmega6450p
#elif defined(__AVR_ATmega645A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega645a 1
#define ARDO_MCU_ARCH_NAME atmega645a
#elif defined(__AVR_ATmega645P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega645p 1
#define ARDO_MCU_ARCH_NAME atmega645p
#elif defined(__AVR_ATmega649__)
#define ARDO_MCU_ARCH_INCLUDE_atmega649 1
#define ARDO_MCU_ARCH_NAME atmega649
#elif defined(__AVR_ATmega6490__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6490 1
#define ARDO_MCU_ARCH_NAME atmega6490
#elif defined(__AVR_ATmega6490A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6490a 1
#define ARDO_MCU_ARCH_NAME atmega6490a
#elif defined(__AVR_ATmega6490P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega6490p 1
#define ARDO_MCU_ARCH_NAME atmega6490p
#elif defined(__AVR_ATmega649A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega649a 1
#define ARDO_MCU_ARCH_NAME atmega649a
#elif defined(__AVR_ATmega649P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega649p 1
#define ARDO_MCU_ARCH_NAME atmega649p
#elif defined(__AVR_ATmega64A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64a 1
#define ARDO_MCU_ARCH_NAME atmega64a
#elif defined(__AVR_ATmega64C1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64c1 1
#define ARDO_MCU_ARCH_NAME atmega64c1
#elif defined(__AVR_ATmega64HVE__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64hve 1
#define ARDO_MCU_ARCH_NAME atmega64hve
#elif defined(__AVR_ATmega64HVE2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64hve2 1
#define ARDO_MCU_ARCH_NAME atmega64hve2
#elif defined(__AVR_ATmega64M1__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64m1 1
#define ARDO_MCU_ARCH_NAME atmega64m1
#elif defined(__AVR_ATmega64RFR2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega64rfr2 1
#define ARDO_MCU_ARCH_NAME atmega64rfr2
#elif defined(__AVR_ATmega8__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8 1
#define ARDO_MCU_ARCH_NAME atmega8
#elif defined(__AVR_ATmega808__)
#define ARDO_MCU_ARCH_INCLUDE_atmega808 1
#define ARDO_MCU_ARCH_NAME atmega808
#elif defined(__AVR_ATmega809__)
#define ARDO_MCU_ARCH_INCLUDE_atmega809 1
#define ARDO_MCU_ARCH_NAME atmega809
#elif defined(__AVR_ATmega8515__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8515 1
#define ARDO_MCU_ARCH_NAME atmega8515
#elif defined(__AVR_ATmega8535__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8535 1
#define ARDO_MCU_ARCH_NAME atmega8535
#elif defined(__AVR_ATmega88__)
#define ARDO_MCU_ARCH_INCLUDE_atmega88 1
#define ARDO_MCU_ARCH_NAME atmega88
#elif defined(__AVR_ATmega88A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega88a 1
#define ARDO_MCU_ARCH_NAME atmega88a
#elif defined(__AVR_ATmega88P__)
#define ARDO_MCU_ARCH_INCLUDE_atmega88p 1
#define ARDO_MCU_ARCH_NAME atmega88p
#elif defined(__AVR_ATmega88PA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega88pa 1
#define ARDO_MCU_ARCH_NAME atmega88pa
#elif defined(__AVR_ATmega88PB__)
#define ARDO_MCU_ARCH_INCLUDE_atmega88pb 1
#define ARDO_MCU_ARCH_NAME atmega88pb
#elif defined(__AVR_ATmega8A__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8a 1
#define ARDO_MCU_ARCH_NAME atmega8a
#elif defined(__AVR_ATmega8HVA__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8hva 1
#define ARDO_MCU_ARCH_NAME atmega8hva
#elif defined(__AVR_ATmega8U2__)
#define ARDO_MCU_ARCH_INCLUDE_atmega8u2 1
#define ARDO_MCU_ARCH_NAME atmega8u2
#elif defined(__AVR_ATtiny10__)
#define ARDO_MCU_ARCH_INCLUDE_attiny10 1
#define ARDO_MCU_ARCH_NAME attiny10
#elif defined(__AVR_ATtiny102__)
#define ARDO_MCU_ARCH_INCLUDE_attiny102 1
#define ARDO_MCU_ARCH_NAME attiny102
#elif defined(__AVR_ATtiny104__)
#define ARDO_MCU_ARCH_INCLUDE_attiny104 1
#define ARDO_MCU_ARCH_NAME attiny104
#elif defined(__AVR_ATtiny11__)
#define ARDO_MCU_ARCH_INCLUDE_attiny11 1
#define ARDO_MCU_ARCH_NAME attiny11
#elif defined(__AVR_ATtiny12__)
#define ARDO_MCU_ARCH_INCLUDE_attiny12 1
#define ARDO_MCU_ARCH_NAME attiny12
#elif defined(__AVR_ATtiny13__)
#define ARDO_MCU_ARCH_INCLUDE_attiny13 1
#define ARDO_MCU_ARCH_NAME attiny13
#elif defined(__AVR_ATtiny13A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny13a 1
#define ARDO_MCU_ARCH_NAME attiny13a
#elif defined(__AVR_ATtiny15__)
#define ARDO_MCU_ARCH_INCLUDE_attiny15 1
#define ARDO_MCU_ARCH_NAME attiny15
#elif defined(__AVR_ATtiny1604__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1604 1
#define ARDO_MCU_ARCH_NAME attiny1604
#elif defined(__AVR_ATtiny1606__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1606 1
#define ARDO_MCU_ARCH_NAME attiny1606
#elif defined(__AVR_ATtiny1607__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1607 1
#define ARDO_MCU_ARCH_NAME attiny1607
#elif defined(__AVR_ATtiny1614__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1614 1
#define ARDO_MCU_ARCH_NAME attiny1614
#elif defined(__AVR_ATtiny1616__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1616 1
#define ARDO_MCU_ARCH_NAME attiny1616
#elif defined(__AVR_ATtiny1617__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1617 1
#define ARDO_MCU_ARCH_NAME attiny1617
#elif defined(__AVR_ATtiny1624__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1624 1
#define ARDO_MCU_ARCH_NAME attiny1624
#elif defined(__AVR_ATtiny1626__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1626 1
#define ARDO_MCU_ARCH_NAME attiny1626
#elif defined(__AVR_ATtiny1627__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1627 1
#define ARDO_MCU_ARCH_NAME attiny1627
#elif defined(__AVR_ATtiny1634__)
#define ARDO_MCU_ARCH_INCLUDE_attiny1634 1
#define ARDO_MCU_ARCH_NAME attiny1634
#elif defined(__AVR_ATtiny167__)
#define ARDO_MCU_ARCH_INCLUDE_attiny167 1
#define ARDO_MCU_ARCH_NAME attiny167
#elif defined(__AVR_ATtiny20__)
#define ARDO_MCU_ARCH_INCLUDE_attiny20 1
#define ARDO_MCU_ARCH_NAME attiny20
#elif defined(__AVR_ATtiny202__)
#define ARDO_MCU_ARCH_INCLUDE_attiny202 1
#define ARDO_MCU_ARCH_NAME attiny202
#elif defined(__AVR_ATtiny204__)
#define ARDO_MCU_ARCH_INCLUDE_attiny204 1
#define ARDO_MCU_ARCH_NAME attiny204
#elif defined(__AVR_ATtiny212__)
#define ARDO_MCU_ARCH_INCLUDE_attiny212 1
#define ARDO_MCU_ARCH_NAME attiny212
#elif defined(__AVR_ATtiny214__)
#define ARDO_MCU_ARCH_INCLUDE_attiny214 1
#define ARDO_MCU_ARCH_NAME attiny214
#elif defined(__AVR_ATtiny22__)
#define ARDO_MCU_ARCH_INCLUDE_attiny22 1
#define ARDO_MCU_ARCH_NAME attiny22
#elif defined(__AVR_ATtiny2313__)
#define ARDO_MCU_ARCH_INCLUDE_attiny2313 1
#define ARDO_MCU_ARCH_NAME attiny2313
#elif defined(__AVR_ATtiny2313A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny2313a 1
#define ARDO_MCU_ARCH_NAME attiny2313a
#elif defined(__AVR_ATtiny24__)
#define ARDO_MCU_ARCH_INCLUDE_attiny24 1
#define ARDO_MCU_ARCH_NAME attiny24
#elif defined(__AVR_ATtiny24A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny24a 1
#define ARDO_MCU_ARCH_NAME attiny24a
#elif defined(__AVR_ATtiny25__)
#define ARDO_MCU_ARCH_INCLUDE_attiny25 1
#define ARDO_MCU_ARCH_NAME attiny25
#elif defined(__AVR_ATtiny26__)
#define ARDO_MCU_ARCH_INCLUDE_attiny26 1
#define ARDO_MCU_ARCH_NAME attiny26
#elif defined(__AVR_ATtiny261__)
#define ARDO_MCU_ARCH_INCLUDE_attiny261 1
#define ARDO_MCU_ARCH_NAME attiny261
#elif defined(__AVR_ATtiny261A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny261a 1
#define ARDO_MCU_ARCH_NAME attiny261a
#elif defined(__AVR_ATtiny28__)
#define ARDO_MCU_ARCH_INCLUDE_attiny28 1
#define ARDO_MCU_ARCH_NAME attiny28
#elif defined(__AVR_ATtiny3214__)
#define ARDO_MCU_ARCH_INCLUDE_attiny3214 1
#define ARDO_MCU_ARCH_NAME attiny3214
#elif defined(__AVR_ATtiny3216__)
#define ARDO_MCU_ARCH_INCLUDE_attiny3216 1
#define ARDO_MCU_ARCH_NAME attiny3216
#elif defined(__AVR_ATtiny3217__)
#define ARDO_MCU_ARCH_INCLUDE_attiny3217 1
#define ARDO_MCU_ARCH_NAME attiny3217
#elif defined(__AVR_ATtiny4__)
#define ARDO_MCU_ARCH_INCLUDE_attiny4 1
#define ARDO_MCU_ARCH_NAME attiny4
#elif defined(__AVR_ATtiny40__)
#define ARDO_MCU_ARCH_INCLUDE_attiny40 1
#define ARDO_MCU_ARCH_NAME attiny40
#elif defined(__AVR_ATtiny402__)
#define ARDO_MCU_ARCH_INCLUDE_attiny402 1
#define ARDO_MCU_ARCH_NAME attiny402
#elif defined(__AVR_ATtiny404__)
#define ARDO_MCU_ARCH_INCLUDE_attiny404 1
#define ARDO_MCU_ARCH_NAME attiny404
#elif defined(__AVR_ATtiny406__)
#define ARDO_MCU_ARCH_INCLUDE_attiny406 1
#define ARDO_MCU_ARCH_NAME attiny406
#elif defined(__AVR_ATtiny412__)
#define ARDO_MCU_ARCH_INCLUDE_attiny412 1
#define ARDO_MCU_ARCH_NAME attiny412
#elif defined(__AVR_ATtiny414__)
#define ARDO_MCU_ARCH_INCLUDE_attiny414 1
#define ARDO_MCU_ARCH_NAME attiny414
#elif defined(__AVR_ATtiny416__)
#define ARDO_MCU_ARCH_INCLUDE_attiny416 1
#define ARDO_MCU_ARCH_NAME attiny416
#elif defined(__AVR_ATtiny417__)
#define ARDO_MCU_ARCH_INCLUDE_attiny417 1
#define ARDO_MCU_ARCH_NAME attiny417
#elif defined(__AVR_ATtiny4313__)
#define ARDO_MCU_ARCH_INCLUDE_attiny4313 1
#define ARDO_MCU_ARCH_NAME attiny4313
#elif defined(__AVR_ATtiny43U__)
#define ARDO_MCU_ARCH_INCLUDE_attiny43u 1
#define ARDO_MCU_ARCH_NAME attiny43u
#elif defined(__AVR_ATtiny44__)
#define ARDO_MCU_ARCH_INCLUDE_attiny44 1
#define ARDO_MCU_ARCH_NAME attiny44
#elif defined(__AVR_ATtiny441__)
#define ARDO_MCU_ARCH_INCLUDE_attiny441 1
#define ARDO_MCU_ARCH_NAME attiny441
#elif defined(__AVR_ATtiny44A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny44a 1
#define ARDO_MCU_ARCH_NAME attiny44a
#elif defined(__AVR_ATtiny45__)
#define ARDO_MCU_ARCH_INCLUDE_attiny45 1
#define ARDO_MCU_ARCH_NAME attiny45
#elif defined(__AVR_ATtiny461__)
#define ARDO_MCU_ARCH_INCLUDE_attiny461 1
#define ARDO_MCU_ARCH_NAME attiny461
#elif defined(__AVR_ATtiny461A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny461a 1
#define ARDO_MCU_ARCH_NAME attiny461a
#elif defined(__AVR_ATtiny48__)
#define ARDO_MCU_ARCH_INCLUDE_attiny48 1
#define ARDO_MCU_ARCH_NAME attiny48
#elif defined(__AVR_ATtiny5__)
#define ARDO_MCU_ARCH_INCLUDE_attiny5 1
#define ARDO_MCU_ARCH_NAME attiny5
#elif defined(__AVR_ATtiny804__)
#define ARDO_MCU_ARCH_INCLUDE_attiny804 1
#define ARDO_MCU_ARCH_NAME attiny804
#elif defined(__AVR_ATtiny806__)
#define ARDO_MCU_ARCH_INCLUDE_attiny806 1
#define ARDO_MCU_ARCH_NAME attiny806
#elif defined(__AVR_ATtiny807__)
#define ARDO_MCU_ARCH_INCLUDE_attiny807 1
#define ARDO_MCU_ARCH_NAME attiny807
#elif defined(__AVR_ATtiny814__)
#define ARDO_MCU_ARCH_INCLUDE_attiny814 1
#define ARDO_MCU_ARCH_NAME attiny814
#elif defined(__AVR_ATtiny816__)
#define ARDO_MCU_ARCH_INCLUDE_attiny816 1
#define ARDO_MCU_ARCH_NAME attiny816
#elif defined(__AVR_ATtiny817__)
#define ARDO_MCU_ARCH_INCLUDE_attiny817 1
#define ARDO_MCU_ARCH_NAME attiny817
#elif defined(__AVR_ATtiny828__)
#define ARDO_MCU_ARCH_INCLUDE_attiny828 1
#define ARDO_MCU_ARCH_NAME attiny828
#elif defined(__AVR_ATtiny84__)
#define ARDO_MCU_ARCH_INCLUDE_attiny84 1
#define ARDO_MCU_ARCH_NAME attiny84
#elif defined(__AVR_ATtiny841__)
#define ARDO_MCU_ARCH_INCLUDE_attiny841 1
#define ARDO_MCU_ARCH_NAME attiny841
#elif defined(__AVR_ATtiny84A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny84a 1
#define ARDO_MCU_ARCH_NAME attiny84a
#elif defined(__AVR_ATtiny85__)
#define ARDO_MCU_ARCH_INCLUDE_attiny85 1
#define ARDO_MCU_ARCH_NAME attiny85
#elif defined(__AVR_ATtiny861__)
#define ARDO_MCU_ARCH_INCLUDE_attiny861 1
#define ARDO_MCU_ARCH_NAME attiny861
#elif defined(__AVR_ATtiny861A__)
#define ARDO_MCU_ARCH_INCLUDE_attiny861a 1
#define ARDO_MCU_ARCH_NAME attiny861a
#elif defined(__AVR_ATtiny87__)
#define ARDO_MCU_ARCH_INCLUDE_attiny87 1
#define ARDO_MCU_ARCH_NAME attiny87
#elif defined(__AVR_ATtiny88__)
#define ARDO_MCU_ARCH_INCLUDE_attiny88 1
#define ARDO_MCU_ARCH_NAME attiny88
#elif defined(__AVR_ATtiny9__)
#define ARDO_MCU_ARCH_INCLUDE_attiny9 1
#define ARDO_MCU_ARCH_NAME attiny9
#elif defined(__AVR_ATxmega128A1__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128a1 1
#define ARDO_MCU_ARCH_NAME atxmega128a1
#elif defined(__AVR_ATxmega128A1U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128a1u 1
#define ARDO_MCU_ARCH_NAME atxmega128a1u
#elif defined(__AVR_ATxmega128A3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128a3 1
#define ARDO_MCU_ARCH_NAME atxmega128a3
#elif defined(__AVR_ATxmega128A3U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128a3u 1
#define ARDO_MCU_ARCH_NAME atxmega128a3u
#elif defined(__AVR_ATxmega128A4U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128a4u 1
#define ARDO_MCU_ARCH_NAME atxmega128a4u
#elif defined(__AVR_ATxmega128B1__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128b1 1
#define ARDO_MCU_ARCH_NAME atxmega128b1
#elif defined(__AVR_ATxmega128B3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128b3 1
#define ARDO_MCU_ARCH_NAME atxmega128b3
#elif defined(__AVR_ATxmega128C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128c3 1
#define ARDO_MCU_ARCH_NAME atxmega128c3
#elif defined(__AVR_ATxmega128D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128d3 1
#define ARDO_MCU_ARCH_NAME atxmega128d3
#elif defined(__AVR_ATxmega128D4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega128d4 1
#define ARDO_MCU_ARCH_NAME atxmega128d4
#elif defined(__AVR_ATxmega16A4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega16a4 1
#define ARDO_MCU_ARCH_NAME atxmega16a4
#elif defined(__AVR_ATxmega16A4U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega16a4u 1
#define ARDO_MCU_ARCH_NAME atxmega16a4u
#elif defined(__AVR_ATxmega16C4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega16c4 1
#define ARDO_MCU_ARCH_NAME atxmega16c4
#elif defined(__AVR_ATxmega16D4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega16d4 1
#define ARDO_MCU_ARCH_NAME atxmega16d4
#elif defined(__AVR_ATxmega16E5__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega16e5 1
#define ARDO_MCU_ARCH_NAME atxmega16e5
#elif defined(__AVR_ATxmega192A3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega192a3 1
#define ARDO_MCU_ARCH_NAME atxmega192a3
#elif defined(__AVR_ATxmega192A3U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega192a3u 1
#define ARDO_MCU_ARCH_NAME atxmega192a3u
#elif defined(__AVR_ATxmega192C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega192c3 1
#define ARDO_MCU_ARCH_NAME atxmega192c3
#elif defined(__AVR_ATxmega192D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega192d3 1
#define ARDO_MCU_ARCH_NAME atxmega192d3
#elif defined(__AVR_ATxmega256A3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256a3 1
#define ARDO_MCU_ARCH_NAME atxmega256a3
#elif defined(__AVR_ATxmega256A3B__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256a3b 1
#define ARDO_MCU_ARCH_NAME atxmega256a3b
#elif defined(__AVR_ATxmega256A3BU__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256a3bu 1
#define ARDO_MCU_ARCH_NAME atxmega256a3bu
#elif defined(__AVR_ATxmega256A3U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256a3u 1
#define ARDO_MCU_ARCH_NAME atxmega256a3u
#elif defined(__AVR_ATxmega256C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256c3 1
#define ARDO_MCU_ARCH_NAME atxmega256c3
#elif defined(__AVR_ATxmega256D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega256d3 1
#define ARDO_MCU_ARCH_NAME atxmega256d3
#elif defined(__AVR_ATxmega32A4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32a4 1
#define ARDO_MCU_ARCH_NAME atxmega32a4
#elif defined(__AVR_ATxmega32A4U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32a4u 1
#define ARDO_MCU_ARCH_NAME atxmega32a4u
#elif defined(__AVR_ATxmega32C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32c3 1
#define ARDO_MCU_ARCH_NAME atxmega32c3
#elif defined(__AVR_ATxmega32C4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32c4 1
#define ARDO_MCU_ARCH_NAME atxmega32c4
#elif defined(__AVR_ATxmega32D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32d3 1
#define ARDO_MCU_ARCH_NAME atxmega32d3
#elif defined(__AVR_ATxmega32D4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32d4 1
#define ARDO_MCU_ARCH_NAME atxmega32d4
#elif defined(__AVR_ATxmega32E5__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega32e5 1
#define ARDO_MCU_ARCH_NAME atxmega32e5
#elif defined(__AVR_ATxmega384C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega384c3 1
#define ARDO_MCU_ARCH_NAME atxmega384c3
#elif defined(__AVR_ATxmega384D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega384d3 1
#define ARDO_MCU_ARCH_NAME atxmega384d3
#elif defined(__AVR_ATxmega64A1__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64a1 1
#define ARDO_MCU_ARCH_NAME atxmega64a1
#elif defined(__AVR_ATxmega64A1U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64a1u 1
#define ARDO_MCU_ARCH_NAME atxmega64a1u
#elif defined(__AVR_ATxmega64A3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64a3 1
#define ARDO_MCU_ARCH_NAME atxmega64a3
#elif defined(__AVR_ATxmega64A3U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64a3u 1
#define ARDO_MCU_ARCH_NAME atxmega64a3u
#elif defined(__AVR_ATxmega64A4U__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64a4u 1
#define ARDO_MCU_ARCH_NAME atxmega64a4u
#elif defined(__AVR_ATxmega64B1__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64b1 1
#define ARDO_MCU_ARCH_NAME atxmega64b1
#elif defined(__AVR_ATxmega64B3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64b3 1
#define ARDO_MCU_ARCH_NAME atxmega64b3
#elif defined(__AVR_ATxmega64C3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64c3 1
#define ARDO_MCU_ARCH_NAME atxmega64c3
#elif defined(__AVR_ATxmega64D3__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64d3 1
#define ARDO_MCU_ARCH_NAME atxmega64d3
#elif defined(__AVR_ATxmega64D4__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega64d4 1
#define ARDO_MCU_ARCH_NAME atxmega64d4
#elif defined(__AVR_ATxmega8E5__)
#define ARDO_MCU_ARCH_INCLUDE_atxmega8e5 1
#define ARDO_MCU_ARCH_NAME atxmega8e5
#elif defined(__AVR_AVR128DA28__)
#define ARDO_MCU_ARCH_INCLUDE_avr128da28 1
#define ARDO_MCU_ARCH_NAME avr128da28
#elif defined(__AVR_AVR128DA32__)
#define ARDO_MCU_ARCH_INCLUDE_avr128da32 1
#define ARDO_MCU_ARCH_NAME avr128da32
#elif defined(__AVR_AVR128DA48__)
#define ARDO_MCU_ARCH_INCLUDE_avr128da48 1
#define ARDO_MCU_ARCH_NAME avr128da48
#elif defined(__AVR_AVR128DA64__)
#define ARDO_MCU_ARCH_INCLUDE_avr128da64 1
#define ARDO_MCU_ARCH_NAME avr128da64
#elif defined(__AVR_M3000__)
#define ARDO_MCU_ARCH_INCLUDE_m3000 1
#define ARDO_MCU_ARCH_NAME m3000
#endif

// Architecture's defines included separately.

#if defined(ARDO_MCU_ARCH_INCLUDE_at43usb320)
#include "ardo_supplemental_at43usb320_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at43usb355)
#include "ardo_supplemental_at43usb355_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at76c711)
#include "ardo_supplemental_at76c711_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at86rf401)
#include "ardo_supplemental_at86rf401_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90c8534)
#include "ardo_supplemental_at90c8534_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90can128)
#include "ardo_supplemental_at90can128_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90can32)
#include "ardo_supplemental_at90can32_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90can64)
#include "ardo_supplemental_at90can64_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm1)
#include "ardo_supplemental_at90pwm1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm161)
#include "ardo_supplemental_at90pwm161_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm2)
#include "ardo_supplemental_at90pwm2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm216)
#include "ardo_supplemental_at90pwm216_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm2b)
#include "ardo_supplemental_at90pwm2b_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm3)
#include "ardo_supplemental_at90pwm3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm316)
#include "ardo_supplemental_at90pwm316_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm3b)
#include "ardo_supplemental_at90pwm3b_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90pwm81)
#include "ardo_supplemental_at90pwm81_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s1200)
#include "ardo_supplemental_at90s1200_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s2313)
#include "ardo_supplemental_at90s2313_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s2323)
#include "ardo_supplemental_at90s2323_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s2333)
#include "ardo_supplemental_at90s2333_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s2343)
#include "ardo_supplemental_at90s2343_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s4414)
#include "ardo_supplemental_at90s4414_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s4433)
#include "ardo_supplemental_at90s4433_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s4434)
#include "ardo_supplemental_at90s4434_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s8515)
#include "ardo_supplemental_at90s8515_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90s8535)
#include "ardo_supplemental_at90s8535_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90scr100)
#include "ardo_supplemental_at90scr100_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb1286)
#include "ardo_supplemental_at90usb1286_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb1287)
#include "ardo_supplemental_at90usb1287_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb162)
#include "ardo_supplemental_at90usb162_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb646)
#include "ardo_supplemental_at90usb646_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb647)
#include "ardo_supplemental_at90usb647_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at90usb82)
#include "ardo_supplemental_at90usb82_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_at94k)
#include "ardo_supplemental_at94k_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5272)
#include "ardo_supplemental_ata5272_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5505)
#include "ardo_supplemental_ata5505_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5702m322)
#include "ardo_supplemental_ata5702m322_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5782)
#include "ardo_supplemental_ata5782_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5790)
#include "ardo_supplemental_ata5790_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5790n)
#include "ardo_supplemental_ata5790n_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5791)
#include "ardo_supplemental_ata5791_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5795)
#include "ardo_supplemental_ata5795_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata5831)
#include "ardo_supplemental_ata5831_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6285)
#include "ardo_supplemental_ata6285_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6286)
#include "ardo_supplemental_ata6286_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6289)
#include "ardo_supplemental_ata6289_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6612c)
#include "ardo_supplemental_ata6612c_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6613c)
#include "ardo_supplemental_ata6613c_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6614q)
#include "ardo_supplemental_ata6614q_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6616c)
#include "ardo_supplemental_ata6616c_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata6617c)
#include "ardo_supplemental_ata6617c_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata664251)
#include "ardo_supplemental_ata664251_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata8210)
#include "ardo_supplemental_ata8210_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_ata8510)
#include "ardo_supplemental_ata8510_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega103)
#include "ardo_supplemental_atmega103_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega128)
#include "ardo_supplemental_atmega128_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1280)
#include "ardo_supplemental_atmega1280_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1281)
#include "ardo_supplemental_atmega1281_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1284)
#include "ardo_supplemental_atmega1284_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1284p)
#include "ardo_supplemental_atmega1284p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1284rfr2)
#include "ardo_supplemental_atmega1284rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega128a)
#include "ardo_supplemental_atmega128a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega128rfa1)
#include "ardo_supplemental_atmega128rfa1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega128rfr2)
#include "ardo_supplemental_atmega128rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16)
#include "ardo_supplemental_atmega16_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1608)
#include "ardo_supplemental_atmega1608_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega1609)
#include "ardo_supplemental_atmega1609_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega161)
#include "ardo_supplemental_atmega161_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega162)
#include "ardo_supplemental_atmega162_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega163)
#include "ardo_supplemental_atmega163_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega164a)
#include "ardo_supplemental_atmega164a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega164p)
#include "ardo_supplemental_atmega164p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega164pa)
#include "ardo_supplemental_atmega164pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega165)
#include "ardo_supplemental_atmega165_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega165a)
#include "ardo_supplemental_atmega165a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega165p)
#include "ardo_supplemental_atmega165p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega165pa)
#include "ardo_supplemental_atmega165pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega168)
#include "ardo_supplemental_atmega168_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega168a)
#include "ardo_supplemental_atmega168a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega168p)
#include "ardo_supplemental_atmega168p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega168pa)
#include "ardo_supplemental_atmega168pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega168pb)
#include "ardo_supplemental_atmega168pb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega169)
#include "ardo_supplemental_atmega169_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega169a)
#include "ardo_supplemental_atmega169a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega169p)
#include "ardo_supplemental_atmega169p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega169pa)
#include "ardo_supplemental_atmega169pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16a)
#include "ardo_supplemental_atmega16a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16hva)
#include "ardo_supplemental_atmega16hva_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16hva2)
#include "ardo_supplemental_atmega16hva2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16hvb)
#include "ardo_supplemental_atmega16hvb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16hvbrevb)
#include "ardo_supplemental_atmega16hvbrevb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16m1)
#include "ardo_supplemental_atmega16m1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16u2)
#include "ardo_supplemental_atmega16u2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega16u4)
#include "ardo_supplemental_atmega16u4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega2560)
#include "ardo_supplemental_atmega2560_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega2561)
#include "ardo_supplemental_atmega2561_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega2564rfr2)
#include "ardo_supplemental_atmega2564rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega256rfr2)
#include "ardo_supplemental_atmega256rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32)
#include "ardo_supplemental_atmega32_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3208)
#include "ardo_supplemental_atmega3208_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3209)
#include "ardo_supplemental_atmega3209_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega323)
#include "ardo_supplemental_atmega323_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega324a)
#include "ardo_supplemental_atmega324a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega324p)
#include "ardo_supplemental_atmega324p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega324pa)
#include "ardo_supplemental_atmega324pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega324pb)
#include "ardo_supplemental_atmega324pb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega325)
#include "ardo_supplemental_atmega325_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3250)
#include "ardo_supplemental_atmega3250_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3250a)
#include "ardo_supplemental_atmega3250a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3250p)
#include "ardo_supplemental_atmega3250p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3250pa)
#include "ardo_supplemental_atmega3250pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega325a)
#include "ardo_supplemental_atmega325a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega325p)
#include "ardo_supplemental_atmega325p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega325pa)
#include "ardo_supplemental_atmega325pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega328)
#include "ardo_supplemental_atmega328_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega328p)
#include "ardo_supplemental_atmega328p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega328pb)
#include "ardo_supplemental_atmega328pb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega329)
#include "ardo_supplemental_atmega329_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3290)
#include "ardo_supplemental_atmega3290_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3290a)
#include "ardo_supplemental_atmega3290a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3290p)
#include "ardo_supplemental_atmega3290p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega3290pa)
#include "ardo_supplemental_atmega3290pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega329a)
#include "ardo_supplemental_atmega329a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega329p)
#include "ardo_supplemental_atmega329p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega329pa)
#include "ardo_supplemental_atmega329pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32a)
#include "ardo_supplemental_atmega32a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32c1)
#include "ardo_supplemental_atmega32c1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32hvb)
#include "ardo_supplemental_atmega32hvb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32hvbrevb)
#include "ardo_supplemental_atmega32hvbrevb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32m1)
#include "ardo_supplemental_atmega32m1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32u2)
#include "ardo_supplemental_atmega32u2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32u4)
#include "ardo_supplemental_atmega32u4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega32u6)
#include "ardo_supplemental_atmega32u6_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega406)
#include "ardo_supplemental_atmega406_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega48)
#include "ardo_supplemental_atmega48_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega4808)
#include "ardo_supplemental_atmega4808_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega4809)
#include "ardo_supplemental_atmega4809_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega48a)
#include "ardo_supplemental_atmega48a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega48p)
#include "ardo_supplemental_atmega48p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega48pa)
#include "ardo_supplemental_atmega48pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega48pb)
#include "ardo_supplemental_atmega48pb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64)
#include "ardo_supplemental_atmega64_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega640)
#include "ardo_supplemental_atmega640_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega644)
#include "ardo_supplemental_atmega644_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega644a)
#include "ardo_supplemental_atmega644a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega644p)
#include "ardo_supplemental_atmega644p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega644pa)
#include "ardo_supplemental_atmega644pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega644rfr2)
#include "ardo_supplemental_atmega644rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega645)
#include "ardo_supplemental_atmega645_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6450)
#include "ardo_supplemental_atmega6450_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6450a)
#include "ardo_supplemental_atmega6450a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6450p)
#include "ardo_supplemental_atmega6450p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega645a)
#include "ardo_supplemental_atmega645a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega645p)
#include "ardo_supplemental_atmega645p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega649)
#include "ardo_supplemental_atmega649_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6490)
#include "ardo_supplemental_atmega6490_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6490a)
#include "ardo_supplemental_atmega6490a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega6490p)
#include "ardo_supplemental_atmega6490p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega649a)
#include "ardo_supplemental_atmega649a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega649p)
#include "ardo_supplemental_atmega649p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64a)
#include "ardo_supplemental_atmega64a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64c1)
#include "ardo_supplemental_atmega64c1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64hve)
#include "ardo_supplemental_atmega64hve_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64hve2)
#include "ardo_supplemental_atmega64hve2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64m1)
#include "ardo_supplemental_atmega64m1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega64rfr2)
#include "ardo_supplemental_atmega64rfr2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8)
#include "ardo_supplemental_atmega8_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega808)
#include "ardo_supplemental_atmega808_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega809)
#include "ardo_supplemental_atmega809_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8515)
#include "ardo_supplemental_atmega8515_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8535)
#include "ardo_supplemental_atmega8535_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega88)
#include "ardo_supplemental_atmega88_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega88a)
#include "ardo_supplemental_atmega88a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega88p)
#include "ardo_supplemental_atmega88p_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega88pa)
#include "ardo_supplemental_atmega88pa_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega88pb)
#include "ardo_supplemental_atmega88pb_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8a)
#include "ardo_supplemental_atmega8a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8hva)
#include "ardo_supplemental_atmega8hva_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atmega8u2)
#include "ardo_supplemental_atmega8u2_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny10)
#include "ardo_supplemental_attiny10_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny102)
#include "ardo_supplemental_attiny102_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny104)
#include "ardo_supplemental_attiny104_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny11)
#include "ardo_supplemental_attiny11_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny12)
#include "ardo_supplemental_attiny12_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny13)
#include "ardo_supplemental_attiny13_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny13a)
#include "ardo_supplemental_attiny13a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny15)
#include "ardo_supplemental_attiny15_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1604)
#include "ardo_supplemental_attiny1604_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1606)
#include "ardo_supplemental_attiny1606_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1607)
#include "ardo_supplemental_attiny1607_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1614)
#include "ardo_supplemental_attiny1614_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1616)
#include "ardo_supplemental_attiny1616_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1617)
#include "ardo_supplemental_attiny1617_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1624)
#include "ardo_supplemental_attiny1624_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1626)
#include "ardo_supplemental_attiny1626_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1627)
#include "ardo_supplemental_attiny1627_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny1634)
#include "ardo_supplemental_attiny1634_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny167)
#include "ardo_supplemental_attiny167_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny20)
#include "ardo_supplemental_attiny20_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny202)
#include "ardo_supplemental_attiny202_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny204)
#include "ardo_supplemental_attiny204_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny212)
#include "ardo_supplemental_attiny212_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny214)
#include "ardo_supplemental_attiny214_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny22)
#include "ardo_supplemental_attiny22_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny2313)
#include "ardo_supplemental_attiny2313_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny2313a)
#include "ardo_supplemental_attiny2313a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny24)
#include "ardo_supplemental_attiny24_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny24a)
#include "ardo_supplemental_attiny24a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny25)
#include "ardo_supplemental_attiny25_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny26)
#include "ardo_supplemental_attiny26_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny261)
#include "ardo_supplemental_attiny261_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny261a)
#include "ardo_supplemental_attiny261a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny28)
#include "ardo_supplemental_attiny28_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny3214)
#include "ardo_supplemental_attiny3214_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny3216)
#include "ardo_supplemental_attiny3216_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny3217)
#include "ardo_supplemental_attiny3217_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny4)
#include "ardo_supplemental_attiny4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny40)
#include "ardo_supplemental_attiny40_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny402)
#include "ardo_supplemental_attiny402_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny404)
#include "ardo_supplemental_attiny404_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny406)
#include "ardo_supplemental_attiny406_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny412)
#include "ardo_supplemental_attiny412_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny414)
#include "ardo_supplemental_attiny414_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny416)
#include "ardo_supplemental_attiny416_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny417)
#include "ardo_supplemental_attiny417_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny4313)
#include "ardo_supplemental_attiny4313_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny43u)
#include "ardo_supplemental_attiny43u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny44)
#include "ardo_supplemental_attiny44_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny441)
#include "ardo_supplemental_attiny441_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny44a)
#include "ardo_supplemental_attiny44a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny45)
#include "ardo_supplemental_attiny45_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny461)
#include "ardo_supplemental_attiny461_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny461a)
#include "ardo_supplemental_attiny461a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny48)
#include "ardo_supplemental_attiny48_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny5)
#include "ardo_supplemental_attiny5_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny804)
#include "ardo_supplemental_attiny804_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny806)
#include "ardo_supplemental_attiny806_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny807)
#include "ardo_supplemental_attiny807_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny814)
#include "ardo_supplemental_attiny814_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny816)
#include "ardo_supplemental_attiny816_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny817)
#include "ardo_supplemental_attiny817_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny828)
#include "ardo_supplemental_attiny828_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny84)
#include "ardo_supplemental_attiny84_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny841)
#include "ardo_supplemental_attiny841_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny84a)
#include "ardo_supplemental_attiny84a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny85)
#include "ardo_supplemental_attiny85_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny861)
#include "ardo_supplemental_attiny861_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny861a)
#include "ardo_supplemental_attiny861a_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny87)
#include "ardo_supplemental_attiny87_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny88)
#include "ardo_supplemental_attiny88_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_attiny9)
#include "ardo_supplemental_attiny9_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128a1)
#include "ardo_supplemental_atxmega128a1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128a1u)
#include "ardo_supplemental_atxmega128a1u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128a3)
#include "ardo_supplemental_atxmega128a3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128a3u)
#include "ardo_supplemental_atxmega128a3u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128a4u)
#include "ardo_supplemental_atxmega128a4u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128b1)
#include "ardo_supplemental_atxmega128b1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128b3)
#include "ardo_supplemental_atxmega128b3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128c3)
#include "ardo_supplemental_atxmega128c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128d3)
#include "ardo_supplemental_atxmega128d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega128d4)
#include "ardo_supplemental_atxmega128d4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega16a4)
#include "ardo_supplemental_atxmega16a4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega16a4u)
#include "ardo_supplemental_atxmega16a4u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega16c4)
#include "ardo_supplemental_atxmega16c4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega16d4)
#include "ardo_supplemental_atxmega16d4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega16e5)
#include "ardo_supplemental_atxmega16e5_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega192a3)
#include "ardo_supplemental_atxmega192a3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega192a3u)
#include "ardo_supplemental_atxmega192a3u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega192c3)
#include "ardo_supplemental_atxmega192c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega192d3)
#include "ardo_supplemental_atxmega192d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256a3)
#include "ardo_supplemental_atxmega256a3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256a3b)
#include "ardo_supplemental_atxmega256a3b_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256a3bu)
#include "ardo_supplemental_atxmega256a3bu_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256a3u)
#include "ardo_supplemental_atxmega256a3u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256c3)
#include "ardo_supplemental_atxmega256c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega256d3)
#include "ardo_supplemental_atxmega256d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32a4)
#include "ardo_supplemental_atxmega32a4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32a4u)
#include "ardo_supplemental_atxmega32a4u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32c3)
#include "ardo_supplemental_atxmega32c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32c4)
#include "ardo_supplemental_atxmega32c4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32d3)
#include "ardo_supplemental_atxmega32d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32d4)
#include "ardo_supplemental_atxmega32d4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega32e5)
#include "ardo_supplemental_atxmega32e5_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega384c3)
#include "ardo_supplemental_atxmega384c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega384d3)
#include "ardo_supplemental_atxmega384d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64a1)
#include "ardo_supplemental_atxmega64a1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64a1u)
#include "ardo_supplemental_atxmega64a1u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64a3)
#include "ardo_supplemental_atxmega64a3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64a3u)
#include "ardo_supplemental_atxmega64a3u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64a4u)
#include "ardo_supplemental_atxmega64a4u_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64b1)
#include "ardo_supplemental_atxmega64b1_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64b3)
#include "ardo_supplemental_atxmega64b3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64c3)
#include "ardo_supplemental_atxmega64c3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64d3)
#include "ardo_supplemental_atxmega64d3_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega64d4)
#include "ardo_supplemental_atxmega64d4_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_atxmega8e5)
#include "ardo_supplemental_atxmega8e5_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_avr128da28)
#include "ardo_supplemental_avr128da28_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_avr128da32)
#include "ardo_supplemental_avr128da32_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_avr128da48)
#include "ardo_supplemental_avr128da48_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_avr128da64)
#include "ardo_supplemental_avr128da64_dev.h"
#endif

#if defined(ARDO_MCU_ARCH_INCLUDE_m3000)
#include "ardo_supplemental_m3000_dev.h"
#endif


namespace ardo {
namespace sys {
namespace avr {

#if defined(ARDO_MCU_ARCH_NAME)
// The selected compile time MCU architecture namespace aliased as "mcu".
namespace mcu = ARDO_MCU_ARCH_NAMESPACE(ARDO_MCU_ARCH_NAME);
using DefaultSignature = mcu::Signature;
#else
// No MCU architecture selected, use a dummy signature type which
// should result in no resorces being provided for the default MCU type.
struct DefaultSignature {};
#endif

}  // namespace avr
}  // namespace sys
}  // namespace ardo

#endif  // ardo_mcu_avr_defs__h
